import { Component } from '@angular/core';

@Component({
  selector: 'rm-department',
  templateUrl: './department-list.component.html',
  styleUrls: ['./department-list.component.css'],
})
export class DepartmentListComponent {
  pageTitle: string = 'Lecturer Biodata';
  lecturers: any[] = [
    {
      firstName: 'Zainab',
      lastName: 'Buhari',
      status: 'Single',
      gender: 'Female',
      faculty: 'Sciences',
      department: 'Politics',
      email: 'zainab@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
    {
      firstName: 'Ope',
      lastName: 'Shade',
      status: 'Single',
      gender: 'male',
      faculty: 'Sciences',
      department: 'Computer',
      email: 'ope@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
    {
      firstName: 'Jalallat',
      lastName: 'Elrufai',
      status: 'married',
      gender: 'Female',
      faculty: 'Sciences',
      department: 'Politics',
      email: 'jalallat@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
    {
      firstName: 'Helen',
      lastName: 'Ayok',
      status: 'Single',
      gender: 'Female',
      faculty: 'fashion',
      department: 'modelling',
      email: 'helen@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
    {
      firstName: 'Joshua',
      lastName: 'Caleb',
      status: 'Single',
      gender: 'male',
      faculty: 'Religion',
      department: 'Christian Study',
      email: 'joshua@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
    {
      firstName: 'Samson',
      lastName: 'Judith',
      status: 'married',
      gender: 'male',
      faculty: 'Science',
      department: 'Social',
      email: 'samson@gmail.com',
      phoneNo: '08098765432',
      imageEdit: 'assets/editBtn.png',
      imageDel: 'assets/trash.png',
    },
  ];
}
